"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports["default"] = RootLayout;
exports.metadata = void 0;
var _google = require("next/font/google");
require("./globals.css");
var inter = (0, _google.Inter)({
  subsets: ["latin"]
});
var metadata = exports.metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};
function RootLayout(_ref) {
  var children = _ref.children;
  return /*#__PURE__*/React.createElement("html", {
    lang: "en"
  }, /*#__PURE__*/React.createElement("body", {
    className: inter.className
  }, children));
}